## Importing the packages 

In [1]:
import numpy as np
import time
import sys

## List Vs Numpy Array

##### LESS MEMORY

In [2]:
L=range(1000)
print (sys.getsizeof(1)*len(L),'bytes')
arr=np.arange(1000)
print (arr.size*arr.itemsize,'bytes')

(24000, 'bytes')
(8000, 'bytes')


##### FAST AND CONVINENT

In [3]:
SIZE=10000000

L1=range(SIZE)
L2=range(SIZE)

arr1=np.arange(SIZE)
arr2=np.arange(SIZE)

start=time.time()
add_L=[(x+y) for x,y in zip(L1,L2)]
print ('Python list took: ',time.time()-start)


start=time.time()
add_arr=arr1+arr2
print ('Numpy array took: ',time.time()-start)

('Python list took: ', 3.586963176727295)
('Numpy array took: ', 0.0407099723815918)


## Basic Operations

In [4]:
l=np.arange(10)
print type(l)
l

<type 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
l.size

10

In [6]:
l.shape #width and height of the array

(10,)

##### 1-D array

In [7]:
x=np.array([11,2,3,4.8,5])

In [8]:
x.dtype

dtype('float64')

accessing the values in the array

In [9]:
x[4]

5.0

In [10]:
x[0]

11.0

In [11]:
x.ndim

1

##### 2-D array

In [12]:
y=np.arange(10).reshape(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
y.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [14]:
y.ndim

2

In [15]:
y.shape

(2, 5)

##### data types and its size

In [16]:
a=np.arange(5)
a.dtype

dtype('int64')

In [17]:
a.itemsize

8

In [18]:
b=np.array(['Welcome','to','the','school','of','ai'])
b.dtype

dtype('S7')

In [19]:
b.itemsize

7

##### All zeros and ones

In [20]:
c=np.ones((3,2))
c

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
d=np.zeros((5,5))
d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
c+d

ValueError: operands could not be broadcast together with shapes (3,2) (5,5) 

In [23]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [24]:
np.eye(2) 

array([[1., 0.],
       [0., 1.]])

In [25]:
np.random.random((2,2))#always the random values be between 1 and 0

array([[0.54874988, 0.67322597],
       [0.12088437, 0.03409071]])

In [26]:
np.random.normal(1, 2, (3, 3))

array([[1.53848902, 0.86005827, 2.75735521],
       [1.65816811, 2.03447112, 1.62565303],
       [1.01249393, 2.55047523, 1.16314743]])

##### Array Range

In [27]:
np.arange(-10,-1,2)

array([-10,  -8,  -6,  -4,  -2])

In [28]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

##### Mathematical operations

In [30]:
e=np.arange(6).reshape(2,3)
f=np.arange(6,12).reshape(2,3)


In [31]:
e

array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
f

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
e+f

array([[ 6,  8, 10],
       [12, 14, 16]])

In [34]:
e-f

array([[-6, -6, -6],
       [-6, -6, -6]])

In [35]:
e*f

array([[ 0,  7, 16],
       [27, 40, 55]])

In [36]:
e.min()

0

In [37]:
e.max()

5

In [38]:
e.min()+e.max()

5

In [39]:
e.sum()

15

In [40]:
e.sum(axis=0)#columns

array([3, 5, 7])

In [41]:
e.sum(axis=1)#rows

array([ 3, 12])

In [42]:
l1=np.array(l1)
l2=np.array(l2)
np.concatenate([l1,l2])

NameError: name 'l1' is not defined

# Slicing and indexing

In [43]:
p=np.array(['School','Of','AI'])

In [44]:
p[0]

'School'

In [45]:
p[:2]

array(['School', 'Of'], dtype='|S6')

In [46]:
p[1:]

array(['Of', 'AI'], dtype='|S6')

In [47]:
p[-1]

'AI'

In [48]:
q=np.arange(9).reshape(3,3)
q

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
q[0:2,2]

array([2, 5])

In [50]:
q[0:2,0:2]

array([[0, 1],
       [3, 4]])

In [51]:
q[-1]

array([6, 7, 8])

In [52]:
q.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
q

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])